### ISSUE TITLE
Uncaught TypeError on Windows with PHP 8.2

### ISSUE THREAD

**Issue by w33zy** [xrdebug/xrdebug#31]
Running the `xrdebug.phar` on Windows throws an type error with PHP 8.2. 
This is the stack trace.

```sh
$ php .\xrdebug.phar

Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, bool given in phar://G:/Downloads/xrdebug.phar/.box/src/Terminal.php:60
Stack trace:
#0 phar://G:/Downloads/xrdebug.phar/.box/src/Terminal.php(60): trim(false)
#1 phar://G:/Downloads/xrdebug.phar/.box/src/Terminal.php(31): HumbugBox436\KevinGH\RequirementChecker\Terminal::initDimensions()
#2 phar://G:/Downloads/xrdebug.phar/.box/src/Printer.php(28): HumbugBox436\KevinGH\RequirementChecker\Terminal->getWidth()
#3 phar://G:/Downloads/xrdebug.phar/.box/src/Checker.php(17): HumbugBox436\KevinGH\RequirementChecker\Printer->__construct(32, true)
#4 phar://G:/Downloads/xrdebug.phar/.box/bin/check-requirements.php(22): HumbugBox436\KevinGH\RequirementChecker\Checker::checkRequirements()
#5 G:\Downloads\xrdebug.phar(12): require('phar://G:/Downl...')
#6 {main}
  thrown in phar://G:/Downloads/xrdebug.phar/.box/src/Terminal.php on line 60
```

**Comment by rodber** [comment]
Based on the trace it seems to be related to the `box compile` and terminal display. Which terminal software are you using? Try with another terminal software as it seems box fails to detect the window size.

In Windows you could also try the Linux binary on WSL, it should work as-is.

**Comment by w33zy** [comment]
I get the same error with cmd.exe, powershell.exe, git-bash and the new terminal app. As far as terminals for Windows go, that's it.
It works under WSL2 but I would rather full native support, if possible.

**Comment by rodber** [comment]
It seems that I packaged this just before this issue got fixed at upstream: https://github.com/box-project/box/pull/999

At this time you could run it from source. Next revision should include the fix above.

**Comment by rodber** [comment]
It works https://github.com/chevere/xrdebug/releases/download/1.0.0-update/xrdebug.phar

**Comment by rodber** [comment]
https://github.com/xrdebug/xrdebug/releases/tag/1.0.1
